"""
Ablation study runner for the MedAI RAG pipeline.

Experiment 1: Full pipeline  (LAQA + MRL + RAG + Generation)
Experiment 2: No LAQA        (MRL + RAG + Generation, single query)
Experiment 3: No LAQA + MRL  (RAG + Generation, full 384-dim embeddings)
Experiment 4: No RAG         (Direct question → LLM, no retrieval)

LAQA  = LLM-Augmented Query Augmentation: generate N paraphrases of the
        question, retrieve for each, then merge results by max score.
MRL   = Matryoshka Representation Learning truncation: use only the first
        MRL_DIM dimensions of the embedding (simulates a smaller MRL model).
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import List, Optional

import numpy as np

from src.generation.service import GenerationService, parse_final_answer, parse_reasoning_steps, fallback_reasoning_steps
from src.models import RetrievedContext
from src.prompt.builder import PromptBuilder
from src.retrieval.vector_store import VectorStore
from src.safety.checker import SafetyChecker

# MRL truncation dimension (simulates a 128-dim Matryoshka sub-embedding)
MRL_DIM = 128
# Number of augmented queries generated by LAQA
LAQA_N = 3


# ---------------------------------------------------------------------------
# Response schema
# ---------------------------------------------------------------------------

@dataclass
class AblationResult:
    experiment: str
    description: str
    final_answer: str
    reasoning_steps: List[str]
    sources: List[dict]
    confidence_score: float
    retrieval_ms: int
    generation_ms: int
    total_ms: int
    blocked: bool
    block_reason: Optional[str] = None
    augmented_queries: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _normalize(vec: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vec)
    return vec / norm if norm > 0 else vec


def _mrl_embed(embedding_service, text: str, use_mrl: bool) -> np.ndarray:
    """Embed text; if use_mrl, truncate to MRL_DIM and re-normalise."""
    vec = embedding_service.embed(text).astype("float32")
    if use_mrl:
        vec = _normalize(vec[:MRL_DIM])
    return vec


def _search(vector_store: VectorStore, query_vec: np.ndarray, k: int, use_mrl: bool):
    """Search the FAISS index, handling MRL dimension mismatch via padding."""
    if use_mrl:
        # Pad truncated vector back to full index dimension for FAISS search
        full_dim = vector_store.index.d
        padded = np.zeros(full_dim, dtype="float32")
        padded[:MRL_DIM] = query_vec
        query_vec = padded
    q = query_vec.reshape(1, -1)
    scores, indices = vector_store.index.search(q, k)
    return scores[0], indices[0]


def _retrieve_single(embedding_service, vector_store: VectorStore,
                     query: str, k: int, use_mrl: bool) -> List[RetrievedContext]:
    vec = _mrl_embed(embedding_service, query, use_mrl)
    scores, indices = _search(vector_store, vec, k, use_mrl)
    contexts: List[RetrievedContext] = []
    for rank, (score, idx) in enumerate(zip(scores, indices), start=1):
        if idx < 0 or idx >= len(vector_store.metadata):
            continue
        contexts.append(RetrievedContext(
            chunk=vector_store.metadata[idx],
            similarity_score=float(score),
            rank=rank,
        ))
    return contexts


def _merge_contexts(all_contexts: List[List[RetrievedContext]], k: int) -> List[RetrievedContext]:
    """Merge multi-query results: keep highest score per chunk id, re-rank."""
    best: dict[str, RetrievedContext] = {}
    for ctxs in all_contexts:
        for c in ctxs:
            cid = c.chunk.id
            if cid not in best or c.similarity_score > best[cid].similarity_score:
                best[cid] = c
    merged = sorted(best.values(), key=lambda c: c.similarity_score, reverse=True)[:k]
    for i, c in enumerate(merged, start=1):
        c.rank = i
    return merged


def _generate_augmented_queries(generation_service: GenerationService,
                                 question: str, n: int) -> List[str]:
    """Ask the LLM to produce N paraphrases of the question for LAQA."""
    prompt = (
        f"Generate {n} different paraphrases of the following medical question. "
        f"Output only the paraphrases, one per line, no numbering.\n\nQuestion: {question}"
    )
    try:
        result = generation_service.generate(prompt)
        lines = [l.strip() for l in result.raw_text.splitlines() if l.strip()]
        # Keep at most n paraphrases; fall back to original if LLM returns nothing useful
        paraphrases = [l for l in lines if len(l.split()) >= 3][:n]
        return paraphrases if paraphrases else [question]
    except Exception:
        return [question]


def _build_sources(contexts: List[RetrievedContext]) -> List[dict]:
    return [
        {
            "sourceFile": c.chunk.source_file,
            "pageNumber": c.chunk.page_number,
            "excerpt": c.chunk.text[:200],
            "similarityScore": c.similarity_score,
        }
        for c in contexts
    ]


def _finalize(
    experiment: str,
    description: str,
    question: str,
    contexts: List[RetrievedContext],
    generation_service: GenerationService,
    prompt_builder: PromptBuilder,
    safety_checker: SafetyChecker,
    retrieval_ms: int,
    augmented_queries: List[str],
) -> AblationResult:
    low_conf = all(c.similarity_score < 0.3 for c in contexts) if contexts else True
    prompt = prompt_builder.build_cot_prompt(question, contexts, low_confidence=low_conf)

    gen_start = time.perf_counter()
    gen = generation_service.generate(prompt)
    generation_ms = int((time.perf_counter() - gen_start) * 1000)

    safety = safety_checker.check(gen.raw_text)
    sources = _build_sources(contexts)
    confidence = max((c.similarity_score for c in contexts), default=0.0)

    if not safety.safe:
        return AblationResult(
            experiment=experiment, description=description,
            final_answer="Response blocked for safety.",
            reasoning_steps=[], sources=sources,
            confidence_score=confidence,
            retrieval_ms=retrieval_ms, generation_ms=generation_ms,
            total_ms=retrieval_ms + generation_ms,
            blocked=True, block_reason=safety.reason,
            augmented_queries=augmented_queries,
        )

    answer = gen.raw_text
    if "This is not medical advice." not in answer:
        answer = answer.rstrip() + "\n\nThis is not medical advice."

    return AblationResult(
        experiment=experiment, description=description,
        final_answer=answer,
        reasoning_steps=gen.reasoning_steps,
        sources=sources,
        confidence_score=confidence,
        retrieval_ms=retrieval_ms, generation_ms=generation_ms,
        total_ms=retrieval_ms + generation_ms,
        blocked=False,
        augmented_queries=augmented_queries,
    )


# ---------------------------------------------------------------------------
# Experiment runners
# ---------------------------------------------------------------------------

def run_exp1_full_pipeline(
    question: str,
    embedding_service,
    vector_store: VectorStore,
    generation_service: GenerationService,
    prompt_builder: PromptBuilder,
    safety_checker: SafetyChecker,
    k: int = 3,
) -> AblationResult:
    """Exp 1: Full pipeline — LAQA + MRL + RAG + Generation."""
    ret_start = time.perf_counter()

    # LAQA: generate augmented queries
    augmented = _generate_augmented_queries(generation_service, question, LAQA_N)
    all_queries = [question] + augmented

    # Retrieve for each query using MRL embeddings
    all_contexts = [_retrieve_single(embedding_service, vector_store, q, k, use_mrl=True)
                    for q in all_queries]
    contexts = _merge_contexts(all_contexts, k)
    retrieval_ms = int((time.perf_counter() - ret_start) * 1000)

    return _finalize(
        "Experiment 1", "Full pipeline (LAQA + MRL + RAG + Generation)",
        question, contexts, generation_service, prompt_builder, safety_checker,
        retrieval_ms, augmented_queries=augmented,
    )


def run_exp2_no_laqa(
    question: str,
    embedding_service,
    vector_store: VectorStore,
    generation_service: GenerationService,
    prompt_builder: PromptBuilder,
    safety_checker: SafetyChecker,
    k: int = 3,
) -> AblationResult:
    """Exp 2: No LAQA — single query, MRL embeddings, RAG + Generation."""
    ret_start = time.perf_counter()
    contexts = _retrieve_single(embedding_service, vector_store, question, k, use_mrl=True)
    contexts.sort(key=lambda c: c.similarity_score, reverse=True)
    retrieval_ms = int((time.perf_counter() - ret_start) * 1000)

    return _finalize(
        "Experiment 2", "No LAQA (MRL + RAG + Generation)",
        question, contexts, generation_service, prompt_builder, safety_checker,
        retrieval_ms, augmented_queries=[],
    )


def run_exp3_no_laqa_no_mrl(
    question: str,
    embedding_service,
    vector_store: VectorStore,
    generation_service: GenerationService,
    prompt_builder: PromptBuilder,
    safety_checker: SafetyChecker,
    k: int = 3,
) -> AblationResult:
    """Exp 3: No LAQA, No MRL — single query, full 384-dim embeddings, RAG + Generation."""
    ret_start = time.perf_counter()
    contexts = _retrieve_single(embedding_service, vector_store, question, k, use_mrl=False)
    contexts.sort(key=lambda c: c.similarity_score, reverse=True)
    retrieval_ms = int((time.perf_counter() - ret_start) * 1000)

    return _finalize(
        "Experiment 3", "No LAQA + No MRL (RAG + Generation, full embeddings)",
        question, contexts, generation_service, prompt_builder, safety_checker,
        retrieval_ms, augmented_queries=[],
    )


def run_exp4_no_rag(
    question: str,
    generation_service: GenerationService,
    safety_checker: SafetyChecker,
) -> AblationResult:
    """Exp 4: No RAG — direct question to LLM, no retrieval."""
    prompt = (
        "System:\nYou are a helpful medical assistant. Answer in plain, simple language.\n\n"
        f"Question: {question}\n\nAnswer:"
    )
    gen_start = time.perf_counter()
    gen = generation_service.generate(prompt)
    generation_ms = int((time.perf_counter() - gen_start) * 1000)

    safety = safety_checker.check(gen.raw_text)
    if not safety.safe:
        return AblationResult(
            experiment="Experiment 4", description="No RAG (Direct LLM, no retrieval)",
            final_answer="Response blocked for safety.",
            reasoning_steps=[], sources=[],
            confidence_score=0.0,
            retrieval_ms=0, generation_ms=generation_ms,
            total_ms=generation_ms,
            blocked=True, block_reason=safety.reason,
        )

    answer = gen.raw_text
    if "This is not medical advice." not in answer:
        answer = answer.rstrip() + "\n\nThis is not medical advice."

    return AblationResult(
        experiment="Experiment 4", description="No RAG (Direct LLM, no retrieval)",
        final_answer=answer,
        reasoning_steps=gen.reasoning_steps,
        sources=[],
        confidence_score=0.0,
        retrieval_ms=0, generation_ms=generation_ms,
        total_ms=generation_ms,
        blocked=False,
    )
